export const FETCH_BRAND_PENDING="FETCH_BRAND_PENDING"
export const FETCH_ALLBRAND_SUCCESS="FETCH_ALLBRAND_SUCCESS"
export const FETCH_BRAND_FAIL="FETCH_BRAND_FAIL"
export const FETCH_POSTBRAND_SUCCESS="FETCH_POSTBRAND_SUCCESS"
export const FETCH_PUTBRAND_SUCCESS="FETCH_PUTBRAND_SUCCESS"
export const FETCH_DELETEBRAND_SUCCESS="FETCH_DELETEBRAND_SUCCESS"
export const FETCH_SINGLEBRAND_SUCCESS="FETCH_SINGLEBRAND_SUCCESS"



