export const FETCH_CHILDPRODUCT_PENDING = "FETCH_CHILDPRODUCT_PENDING"
export const FETCH_CHILDPRODUCT_SUCCESS = "FETCH_CHILDPRODUCT_SUCCESS"
export const FETCH_CHILDPRODUCT_FAIL = "FETCH_CHILDPRODUCT_FAIL"
