export const FETCH_PRODUCTSALE_PENDING = "FETCH_PRODUCTSALE_PENDING"
export const FETCH_PRODUCTSALE_SUCCESS = "FETCH_PRODUCTSALE_SUCCESS"
export const FETCH_PRODUCTSALE_FAIL = "FETCH_PRODUCTSALE_FAIL"
