export const FETCH_USER_PENDING = "FETCH_USER_PENDING"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAIL = "FETCH_USER_FAIL"
export const FETCH_USER_ISOLOGIN = "FETCH_USER_ISOLOGIN"
export const FETCH_ADMIN_ISOLOGIN = "FETCH_ADMIN_ISOLOGIN"
export const FETCH_USER_DATASINGLE = "FETCH_USER_DATASINGLE"


