export const FETCH_WOMENPRODUCT_PENDING = "FETCH_WOMENPRODUCT_PENDING"
export const FETCH_WOMENPRODUCT_SUCCESS = "FETCH_WOMENPRODUCT_SUCCESS"
export const FETCH_WOMENPRODUCT_FAIL = "FETCH_WOMENPRODUCT_FAIL"
